# Generated by Django 5.2.7 on 2025-10-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('government', '0002_business_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='hr_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='government.business'),
        ),
    ]
